steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/{project_id}/backend:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/{project_id}/backend:$COMMIT_SHA']

 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: 'gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'backend'
   - '--image'
   - 'gcr.io/{project_id}/backend:$COMMIT_SHA'
  #  - '--clear-secrets'
  #  - '--update-secrets=/path/to/credentials/file.json={secret_manager_name}:1'
  #  - '--update-secrets=GOOGLE_APPLICATION_CREDENTIALS={secret_manager_name}:1'
   - '--timeout=3600'
   - '--allow-unauthenticated'
   - '--add-cloudsql-instances'
   - '{project_id}:{INSTANCE_CONNECTION_NAME}'
  #  - '--clear-env-vars'
  #  - '--set-env-vars'
  #  - 'GOOGLE_APPLICATION_CREDENTIALS="/path/to/credentials/file.json"'
  #  - '--set-env-vars'
  #  - 'INSTANCE_UNIX_SOCKET="/cloudsql/{project_id}:{INSTANCE_CONNECTION_NAME}"'
   - '--set-env-vars'
   - 'INSTANCE_CONNECTION_NAME="{project_id}:{INSTANCE_CONNECTION_NAME}"'
   - '--set-env-vars'
   - 'DB_USER="UUUUU"'
   - '--set-env-vars'
   - 'DB_PASS="PPPPP"'
   - '--set-env-vars'
   - 'DB_NAME="NNNNN"'
   - '--set-env-vars'
   - 'VENDOR_TOKEN="VVVVV"'
   - '--region'
   - 'asia-east1'
   - '--port'
   - '8080'
   secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS']
images:
 - 'gcr.io/{project_id}/backend:$COMMIT_SHA'
availableSecrets:
  secretManager:
  - versionName: projects/{project_id}/secrets/{secret_manager_name}/versions/1
    env: 'GOOGLE_APPLICATION_CREDENTIALS'
options:
  logging: CLOUD_LOGGING_ONLY